# Generated by Django 4.0.3 on 2022-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('mydogBreed', models.CharField(max_length=20)),
                ('mydogSize', models.CharField(max_length=3)),
                ('preferFood', models.CharField(max_length=10)),
            ],
        ),
    ]
