# Generated by Django 4.0.3 on 2022-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddungs', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mydogBreed',
            field=models.CharField(max_length=20, verbose_name='견종'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mydogSize',
            field=models.CharField(max_length=3, verbose_name='반려견 크기'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferFood',
            field=models.CharField(max_length=10, verbose_name='선호 사료'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=20, verbose_name='아이디'),
        ),
    ]
